artifact_location: /home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/models/runs/mlflow/352234212747491376
creation_time: 1730686387127
experiment_id: '352234212747491376'
last_update_time: 1730686387127
lifecycle_stage: active
name: /Shared/Ultralytics
