artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/328582223577667305
creation_time: 1730696313678
experiment_id: '328582223577667305'
last_update_time: 1730696313678
lifecycle_stage: active
name: training
