artifact_uri: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/354828383639114554/48e8162cca9b4c26be44acfae217b648/artifacts
end_time: 1730318266127
entry_point_name: ''
experiment_id: '354828383639114554'
lifecycle_stage: active
run_id: 48e8162cca9b4c26be44acfae217b648
run_name: bold-pug-71
run_uuid: 48e8162cca9b4c26be44acfae217b648
source_name: ''
source_type: 4
source_version: ''
start_time: 1730318194111
status: 3
tags: []
user_id: pedro
