artifact_location: /home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/models/runs/mlflow/690435638034751957
creation_time: 1730468428970
experiment_id: '690435638034751957'
last_update_time: 1730468428970
lifecycle_stage: active
name: /Shared/Ultralytics
