artifact_location: /home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/models/runs/mlflow/230552110101969223
creation_time: 1730696318091
experiment_id: '230552110101969223'
last_update_time: 1730696318091
lifecycle_stage: active
name: /Shared/Ultralytics
