artifact_location: /home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/models/runs/mlflow/904578371731350337
creation_time: 1730295037804
experiment_id: '904578371731350337'
last_update_time: 1730295037804
lifecycle_stage: active
name: /Shared/Ultralytics
