artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/354828383639114554
creation_time: 1730295033253
experiment_id: '354828383639114554'
last_update_time: 1730295033253
lifecycle_stage: active
name: starter
