artifact_uri: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/354828383639114554/7095fe781b954dffbdb84e9d273aaa14/artifacts
end_time: 1730297422596
entry_point_name: ''
experiment_id: '354828383639114554'
lifecycle_stage: active
run_id: 7095fe781b954dffbdb84e9d273aaa14
run_name: burly-moose-673
run_uuid: 7095fe781b954dffbdb84e9d273aaa14
source_name: ''
source_type: 4
source_version: ''
start_time: 1730297344191
status: 3
tags: []
user_id: pedro
