artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/103985756613275551
creation_time: 1730686381594
experiment_id: '103985756613275551'
last_update_time: 1730686381594
lifecycle_stage: active
name: training
