artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/494977678092997024
creation_time: 1732208496395
experiment_id: '494977678092997024'
last_update_time: 1732208496395
lifecycle_stage: active
name: /Shared/Ultralytics
