artifact_location: /home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/models/runs/mlflow/136465540338605997
creation_time: 1730398512828
experiment_id: '136465540338605997'
last_update_time: 1730398512828
lifecycle_stage: active
name: /Shared/Ultralytics
