artifact_uri: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/103985756613275551/bbf35f7d49bc447a89ab9a8e5f9a334f/artifacts
end_time: 1730686449173
entry_point_name: ''
experiment_id: '103985756613275551'
lifecycle_stage: active
run_id: bbf35f7d49bc447a89ab9a8e5f9a334f
run_name: stylish-stoat-395
run_uuid: bbf35f7d49bc447a89ab9a8e5f9a334f
source_name: ''
source_type: 4
source_version: ''
start_time: 1730686381631
status: 3
tags: []
user_id: pedro
